Remove all support for scikits.audiolab
Can no longer be installed:

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "…\scikits-audiolab_…\setup.py", line 32, in <module>
          from numpy.distutils.core import setup
      ModuleNotFoundError: No module named 'numpy.distutils'
      [end of output]

This is because:

> numpy.distutils is deprecated, and will be removed for Python >= 3.12.

As mentioned in c324e1a3, it hasn't been updated in 12 years.